'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports ControlsSAP


Public Class Edicion
    Inherits ControlsSAP.SAPObject
    
    Public Sub New(ByVal c As SAPBobsCOM.Company)
        MyBase.New(c, "@IFG_INSDEPPAIS", Nothing, true)
    End Sub
    
    '''<summary>
    '''Código
    '''<br/>Field Name: <i>Code</i>.
    '''</summary>
    Public ReadOnly Property Code() As String
        Get
            Return Me.FilaActual("Code")
        End Get
    End Property
    
    '''<summary>
    '''Descripción
    '''<br/>Field Name: <i>Name</i>.
    '''</summary>
    Public Property Name() As String
        Get
            Return Me.FilaActual("Name")
        End Get
        Set
            Me.FilaActual("Name") = Value
        End Set
    End Property
    
    '''<exclude/>
    Protected Overrides Function InitializeLines() As Long
    End Function
    
    '''<exclude/>
    Protected Overrides Sub ModifyingObject()
    End Sub
End Class
