'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports ControlsSAP


Public Class frmAsistente
    
    Private _company As SAPBobsCOM.Company
    
    Public Sub New(ByVal company As SapBobsCOM.Company)
        MyBase.New
        ' Llamada necesaria para el Diseñador de Windows Forms.
        Me.InitializeComponent
        '
        ' Agregue cualquier inicialización después de la llamada a InitializeComponent().
        _company = company
    End Sub
    
    Private Sub Form_Load(ByVal sender As Object, ByVal e As System.EventArgs)
    End Sub
    
    Private Sub Form_PageChanging(ByVal PreviousPage As Integer, ByRef NextPage As Integer, ByRef Cancel As Boolean)
        Try 
            'Controla que el avance sea hacia adelante
            If (PreviousPage < NextPage) Then
                If (PreviousPage = 0) Then
                    'Insere el código de validación para el cambio de página 'Filtro'
                Else
                    If (PreviousPage = 1) Then
                        'Insere el código de validación para el cambio de página 'Resultado'
                    End If
                End If
            End If
        Catch ex As System.Exception
            ControlsSAP.SAPMsg.Show(ex)
        End Try
    End Sub
    
    Private Sub Form_PageChanged(ByVal PageIndex As Integer)
        Try 
            'Asignación de textos para cada página
            If (PageIndex = 0) Then
                Me.Description = "Filtro para mostrar los resultados en el grid"
            Else
                If (PageIndex = 1) Then
                    Me.Description = "Grid con los resultados"
                End If
            End If
        Catch ex As System.Exception
            ControlsSAP.SAPMsg.Show(ex)
        End Try
    End Sub
    
    Private Sub Form_EndProcess(ByVal sender As Object, ByVal e As System.EventArgs)
        'Código que se ejecutará al pulsar sobre 'Finalizar'
    End Sub
End Class
