'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports ControlsSAP


Partial Public Class frmAsistente
    Inherits ControlsSAP.Forms.FormWizard
    
    'Requerido por el Diseñador de Windows Forms
    Private components As System.ComponentModel.IContainer
    
    Private Page3 As System.Windows.Forms.TabPage
    
    Private Page4 As System.Windows.Forms.TabPage
    
    'Form reemplaza a Dispose para limpiar la lista de componentes.
    <System.Diagnostics.DebuggerNonUserCode()>  _
    Protected Overrides Sub Dispose(ByVal disposing As Boolean)
        If disposing Then
            If (Not (components) Is Nothing) Then
                components.Dispose
            End If
        End If
        MyBase.Dispose(disposing)
    End Sub
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Private Sub InitializeComponent()
        Me.components = New System.ComponentModel.Container()
        AddHandler Load, AddressOf Me.Form_Load
        AddHandler PageChanging, AddressOf Me.Form_PageChanging
        AddHandler PageChanged, AddressOf Me.Form_PageChanged
        AddHandler EndProcess, AddressOf Me.Form_EndProcess
        Page3 = New System.Windows.Forms.TabPage()
        TabControl1.Controls.Add(Page3)
        Me.Page3.Text = "Filtro"
        Page4 = New System.Windows.Forms.TabPage()
        TabControl1.Controls.Add(Page4)
        Me.Page4.Text = "Resultado"
        Me.Text = "frmAsistente"
    End Sub
End Class
