'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports ControlsSAP


<Forms.FormDescription("Países")>  _
Public Class frmEdicion
    
    Private _company As SAPBobsCOM.Company
    
    Private _obj As Edicion
    
    Public Sub New(ByVal company As SapBobsCOM.Company)
        MyBase.New
        ' Llamada necesaria para el Diseñador de Windows Forms.
        Me.InitializeComponent
        '
        ' Agregue cualquier inicialización después de la llamada a InitializeComponent().
        _company = company
    End Sub
    
    Private Sub Form_Load(ByVal sender As Object, ByVal e As System.EventArgs)
        
        'Configuración de los controles
        
        'Configuramos los campos que aparecerán en la busqueda
        Me.ViewColumnInSearch("Code", "Código")
        Me.ViewColumnInSearch("Name", "Descripción")
        
        'Instanciamos el objeto de negocio que utilizará el formulario
        Me._obj = New Edicion(Me._company)
        Me.GetAllObjects(Me._obj)
        Me.GoToLast
        'Control con el foco inicial
        Me.txtCode.Select
    End Sub
    
    Public Overrides Sub DoAdd()
        MyBase.DoAdd
        'Valores iniciales al crear
        Me.txtCode.Select
    End Sub
    
    Public Overrides Sub LoadFormWithObject()
        'Asignamos los valores del objeto en los controles correspondientes
        Me.txtCode.Text = Me._obj.Code
        Me.txtName.Text = Me._obj.Name
    End Sub
    
    Public Overrides Sub LoadObjectWithForm()
        'Asignamos los valores de los controles en las propiedades del objeto que correspondan
        Me._obj.Name = Me.txtName.Text
    End Sub
    
    Private Sub btnOk_Click(ByVal sender As Object, ByVal e As System.EventArgs)
        Try 
            Me.SaveObject
        Catch ex As System.Exception
            ControlsSAP.SAPMsg.Show(ex)
        End Try
    End Sub
    
    Private Sub btnCancel_Click(ByVal sender As Object, ByVal e As System.EventArgs)
        Me.Close
    End Sub
    
    Private Sub Form_AddedSAPObject(ByVal obj As ControlsSAP.SAPObject)
        Me.DoAdd
    End Sub
End Class
