'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports ControlsSAP


Partial Public Class frmEdicion
    Inherits ControlsSAP.Forms.FormEditSAP
    
    'Requerido por el Diseñador de Windows Forms
    Private components As System.ComponentModel.IContainer
    
    Private WithEvents lbltxtCode As ControlsSAP.Controls.SAPLabel
    
    Private WithEvents txtCode As ControlsSAP.Controls.SAPTextBox
    
    Private WithEvents lbltxtName As ControlsSAP.Controls.SAPLabel
    
    Private WithEvents txtName As ControlsSAP.Controls.SAPTextBox
    
    Private WithEvents btnOk As ControlsSAP.Controls.SAPButton
    
    Private WithEvents btnCancel As ControlsSAP.Controls.SAPButton
    
    'Form reemplaza a Dispose para limpiar la lista de componentes.
    <System.Diagnostics.DebuggerNonUserCode()>  _
    Protected Overrides Sub Dispose(ByVal disposing As Boolean)
        If disposing Then
            If (Not (components) Is Nothing) Then
                components.Dispose
            End If
        End If
        MyBase.Dispose(disposing)
    End Sub
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Private Sub InitializeComponent()
        Me.components = New System.ComponentModel.Container()
        lbltxtCode = New ControlsSAP.Controls.SAPLabel()
        Me.Controls.Add(lbltxtCode)
        Me.lbltxtCode.Location = New System.Drawing.Point(8, 30)
        Me.lbltxtCode.Size = New System.Drawing.Size(120, 14)
        Me.lbltxtCode.Text = "Código"
        txtCode = New ControlsSAP.Controls.SAPTextBox()
        Me.Controls.Add(txtCode)
        Me.txtCode.Location = New System.Drawing.Point(128, 30)
        Me.txtCode.Size = New System.Drawing.Size(150, 14)
        Me.txtCode.AcceptsAdd = true
        Me.txtCode.AcceptsUpdate = true
        Me.txtCode.AcceptsSearch = true
        Me.txtCode.CausesActionUpdate = true
        Me.txtCode.CausesAspectChange = true
        Me.txtCode.DataType = ControlsSAP.Controls.SAPTextBox.DataTypes.Cadena
        Me.txtCode.DataSubType = ControlsSAP.Controls.SAPTextBox.DataSubTypes.Ninguno
        lbltxtName = New ControlsSAP.Controls.SAPLabel()
        Me.Controls.Add(lbltxtName)
        Me.lbltxtName.Location = New System.Drawing.Point(8, 45)
        Me.lbltxtName.Size = New System.Drawing.Size(120, 14)
        Me.lbltxtName.Text = "Descripción"
        txtName = New ControlsSAP.Controls.SAPTextBox()
        Me.Controls.Add(txtName)
        Me.txtName.Location = New System.Drawing.Point(128, 45)
        Me.txtName.Size = New System.Drawing.Size(150, 14)
        Me.txtName.AcceptsAdd = true
        Me.txtName.AcceptsUpdate = true
        Me.txtName.AcceptsSearch = true
        Me.txtName.CausesActionUpdate = true
        Me.txtName.CausesAspectChange = true
        Me.txtName.DataType = ControlsSAP.Controls.SAPTextBox.DataTypes.Cadena
        Me.txtName.DataSubType = ControlsSAP.Controls.SAPTextBox.DataSubTypes.Ninguno
        Me.Size = New System.Drawing.Size(165, 108)
        btnOk = New ControlsSAP.Controls.SAPButton()
        Me.Controls.Add(btnOk)
        Me.btnOk.Location = New System.Drawing.Point(8, 70)
        Me.btnOk.Size = New System.Drawing.Size(75, 20)
        Me.btnOk.Text = "OK"
        AddHandler Me.btnOk.Click, AddressOf Me.btnOk_Click
        Me.ButtonForm = Me.btnOK
        btnCancel = New ControlsSAP.Controls.SAPButton()
        Me.Controls.Add(btnCancel)
        Me.btnCancel.Location = New System.Drawing.Point(90, 70)
        Me.btnCancel.Size = New System.Drawing.Size(75, 20)
        Me.btnCancel.Text = "Cancel"
        AddHandler Me.btnCancel.Click, AddressOf Me.btnCancel_Click
        AddHandler Load, AddressOf Me.Form_Load
        Me.AcceptsAdd = true
        Me.AcceptsUpdate = true
        Me.AcceptsSearch = true
        Me.AcceptsDelete = true
        Me.AcceptsExcel = false
        Me.AcceptsPreview = false
        Me.AcceptsPrint = false
        Me.AcceptsWord = false
        AddHandler AddedSAPObject, AddressOf Me.Form_AddedSAPObject
        Me.Text = "Países"
    End Sub
End Class
