'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports ControlsSAP


Public Class frmSAP
    
    Private _company As SAPBobsCOM.Company
    
    Public Sub New(ByVal company As SapBobsCOM.Company)
        MyBase.New
        ' Llamada necesaria para el Diseñador de Windows Forms.
        Me.InitializeComponent
        '
        ' Agregue cualquier inicialización después de la llamada a InitializeComponent().
        _company = company
    End Sub
End Class
