'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports ControlsSAP


Partial Public Class frmSAP
    Inherits ControlsSAP.Forms.FormSAP
    
    'Requerido por el Diseñador de Windows Forms
    Private components As System.ComponentModel.IContainer
    
    'Form reemplaza a Dispose para limpiar la lista de componentes.
    <System.Diagnostics.DebuggerNonUserCode()>  _
    Protected Overrides Sub Dispose(ByVal disposing As Boolean)
        If disposing Then
            If (Not (components) Is Nothing) Then
                components.Dispose
            End If
        End If
        MyBase.Dispose(disposing)
    End Sub
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Private Sub InitializeComponent()
        Me.components = New System.ComponentModel.Container()
    End Sub
End Class
