'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports ControlsSAP


Partial Public Class frmConsultaFaltas
    Inherits ControlsSAP.Forms.FormSAP
    
    'Requerido por el Diseñador de Windows Forms
    Private components As System.ComponentModel.IContainer
    
    'Form reemplaza a Dispose para limpiar la lista de componentes.
    <System.Diagnostics.DebuggerNonUserCode()>  _
    Protected Overrides Sub Dispose(ByVal disposing As Boolean)
        If disposing Then
            If (Not (components) Is Nothing) Then
                components.Dispose
            End If
        End If
        MyBase.Dispose(disposing)
    End Sub
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Private Sub InitializeComponent()
        Me.SapGrid1 = New ControlsSAP.Controls.SAPGrid()
        Me.lblEmp = New ControlsSAP.Controls.SAPLabel()
        Me.lblFechaD = New ControlsSAP.Controls.SAPLabel()
        Me.lstEmp = New ControlsSAP.Controls.SAPListBox()
        Me.txtFechaD = New ControlsSAP.Controls.SAPTextBox()
        Me.lblFechaH = New ControlsSAP.Controls.SAPLabel()
        Me.txtFechaH = New ControlsSAP.Controls.SAPTextBox()
        Me.btnFiltrar = New ControlsSAP.Controls.SAPButton()
        Me.btnModificar = New ControlsSAP.Controls.SAPButton()
        Me.btnAñadir = New ControlsSAP.Controls.SAPButton()
        CType(Me.SapGrid1, System.ComponentModel.ISupportInitialize).BeginInit()
        Me.SuspendLayout()
        '
        'SapGrid1
        '
        Me.SapGrid1.FocusedColumn = Nothing
        Me.SapGrid1.FocusedRowHandle = -2147483648
        Me.SapGrid1.FocusedValue = Nothing
        Me.SapGrid1.FocusIndex = -2147483648
        Me.SapGrid1.Font = New System.Drawing.Font("Tahoma", 10.0!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel, CType(0, Byte))
        Me.SapGrid1.Location = New System.Drawing.Point(0, 85)
        Me.SapGrid1.Name = "SapGrid1"
        Me.SapGrid1.Size = New System.Drawing.Size(631, 221)
        Me.SapGrid1.TabIndex = 1
        '
        'lblEmp
        '
        Me.lblEmp.Location = New System.Drawing.Point(13, 23)
        Me.lblEmp.Margin = New System.Windows.Forms.Padding(0, 0, 0, 1)
        Me.lblEmp.Name = "lblEmp"
        Me.lblEmp.Size = New System.Drawing.Size(120, 14)
        Me.lblEmp.TabIndex = 2
        Me.lblEmp.Text = "Empleado Dep. Ventas"
        '
        'lblFechaD
        '
        Me.lblFechaD.Location = New System.Drawing.Point(15, 42)
        Me.lblFechaD.Margin = New System.Windows.Forms.Padding(0, 0, 0, 1)
        Me.lblFechaD.Name = "lblFechaD"
        Me.lblFechaD.Size = New System.Drawing.Size(120, 14)
        Me.lblFechaD.TabIndex = 3
        Me.lblFechaD.Text = "Fecha Desde"
        '
        'lstEmp
        '
        Me.lstEmp.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle
        Me.lstEmp.Location = New System.Drawing.Point(139, 23)
        Me.lstEmp.Margin = New System.Windows.Forms.Padding(0, 0, 0, 1)
        Me.lstEmp.Name = "lstEmp"
        Me.lstEmp.Size = New System.Drawing.Size(150, 14)
        Me.lstEmp.TabIndex = 1
        '
        'txtFechaD
        '
        Me.txtFechaD.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle
        Me.txtFechaD.DataType = ControlsSAP.Controls.SAPTextBox.DataTypes.Fecha
        Me.txtFechaD.Location = New System.Drawing.Point(139, 41)
        Me.txtFechaD.Margin = New System.Windows.Forms.Padding(0, 0, 0, 1)
        Me.txtFechaD.MaxLength = 10
        Me.txtFechaD.Name = "txtFechaD"
        Me.txtFechaD.Size = New System.Drawing.Size(150, 14)
        Me.txtFechaD.TabIndex = 2
        '
        'lblFechaH
        '
        Me.lblFechaH.Location = New System.Drawing.Point(307, 41)
        Me.lblFechaH.Margin = New System.Windows.Forms.Padding(0, 0, 0, 1)
        Me.lblFechaH.Name = "lblFechaH"
        Me.lblFechaH.Size = New System.Drawing.Size(120, 14)
        Me.lblFechaH.TabIndex = 6
        Me.lblFechaH.Text = "Fecha Hasta"
        '
        'txtFechaH
        '
        Me.txtFechaH.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle
        Me.txtFechaH.DataType = ControlsSAP.Controls.SAPTextBox.DataTypes.Fecha
        Me.txtFechaH.Location = New System.Drawing.Point(431, 42)
        Me.txtFechaH.Margin = New System.Windows.Forms.Padding(0, 0, 0, 1)
        Me.txtFechaH.MaxLength = 10
        Me.txtFechaH.Name = "txtFechaH"
        Me.txtFechaH.Size = New System.Drawing.Size(150, 14)
        Me.txtFechaH.TabIndex = 3
        '
        'btnFiltrar
        '
        Me.btnFiltrar.Location = New System.Drawing.Point(360, 59)
        Me.btnFiltrar.Name = "btnFiltrar"
        Me.btnFiltrar.Size = New System.Drawing.Size(75, 20)
        Me.btnFiltrar.TabIndex = 6
        Me.btnFiltrar.Text = "Filtrar"
        Me.btnFiltrar.UseVisualStyleBackColor = False
        '
        'btnModificar
        '
        Me.btnModificar.Location = New System.Drawing.Point(271, 59)
        Me.btnModificar.Name = "btnModificar"
        Me.btnModificar.Size = New System.Drawing.Size(75, 20)
        Me.btnModificar.TabIndex = 5
        Me.btnModificar.Text = "Modificar"
        Me.btnModificar.UseVisualStyleBackColor = False
        '
        'btnAñadir
        '
        Me.btnAñadir.Location = New System.Drawing.Point(180, 59)
        Me.btnAñadir.Name = "btnAñadir"
        Me.btnAñadir.Size = New System.Drawing.Size(75, 20)
        Me.btnAñadir.TabIndex = 4
        Me.btnAñadir.Text = "Añadir"
        Me.btnAñadir.UseVisualStyleBackColor = False
        '
        'frmConsultaFaltas
        '
        Me.AutoScaleDimensions = New System.Drawing.SizeF(6.0!, 12.0!)
        Me.ClientSize = New System.Drawing.Size(631, 306)
        Me.Controls.Add(Me.btnAñadir)
        Me.Controls.Add(Me.btnModificar)
        Me.Controls.Add(Me.btnFiltrar)
        Me.Controls.Add(Me.txtFechaH)
        Me.Controls.Add(Me.lblFechaH)
        Me.Controls.Add(Me.txtFechaD)
        Me.Controls.Add(Me.lstEmp)
        Me.Controls.Add(Me.lblFechaD)
        Me.Controls.Add(Me.lblEmp)
        Me.Controls.Add(Me.SapGrid1)
        Me.MaximumSize = New System.Drawing.Size(647, 322)
        Me.Name = "frmConsultaFaltas"
        Me.Controls.SetChildIndex(Me.SapGrid1, 0)
        Me.Controls.SetChildIndex(Me.lblEmp, 0)
        Me.Controls.SetChildIndex(Me.lblFechaD, 0)
        Me.Controls.SetChildIndex(Me.lstEmp, 0)
        Me.Controls.SetChildIndex(Me.txtFechaD, 0)
        Me.Controls.SetChildIndex(Me.lblFechaH, 0)
        Me.Controls.SetChildIndex(Me.txtFechaH, 0)
        Me.Controls.SetChildIndex(Me.btnFiltrar, 0)
        Me.Controls.SetChildIndex(Me.btnModificar, 0)
        Me.Controls.SetChildIndex(Me.btnAñadir, 0)
        CType(Me.SapGrid1, System.ComponentModel.ISupportInitialize).EndInit()
        Me.ResumeLayout(False)

    End Sub
    Friend WithEvents SapGrid1 As ControlsSAP.Controls.SAPGrid
    Friend WithEvents lblEmp As ControlsSAP.Controls.SAPLabel
    Friend WithEvents lblFechaD As ControlsSAP.Controls.SAPLabel
    Friend WithEvents lstEmp As ControlsSAP.Controls.SAPListBox
    Friend WithEvents txtFechaD As ControlsSAP.Controls.SAPTextBox
    Friend WithEvents lblFechaH As ControlsSAP.Controls.SAPLabel
    Friend WithEvents txtFechaH As ControlsSAP.Controls.SAPTextBox
    Friend WithEvents btnFiltrar As ControlsSAP.Controls.SAPButton
    Friend WithEvents btnModificar As ControlsSAP.Controls.SAPButton
    Friend WithEvents btnAñadir As ControlsSAP.Controls.SAPButton
End Class
