'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports ControlsSAP


Partial Public Class frmFaltasEDV
    Inherits ControlsSAP.Forms.FormEditSAP
    
    'Requerido por el Diseñador de Windows Forms
    Private components As System.ComponentModel.IContainer
    
    Private WithEvents lbltxtCode As ControlsSAP.Controls.SAPLabel
    
    Private WithEvents txtCode As ControlsSAP.Controls.SAPTextBox
    
    Private WithEvents lbltxtName As ControlsSAP.Controls.SAPLabel
    
    Private WithEvents txtName As ControlsSAP.Controls.SAPTextBox
    
    Private WithEvents lbllstTFG_CODEEMP As ControlsSAP.Controls.SAPLabel
    
    Private WithEvents lstTFG_CODEEMP As ControlsSAP.Controls.SAPListBox
    
    Private WithEvents lbltxtTFG_FECHAFALTA As ControlsSAP.Controls.SAPLabel
    
    Private WithEvents txtTFG_FECHAFALTA As ControlsSAP.Controls.SAPTextBox
    
    Private WithEvents lbltxtTFG_HORASFALTADAS As ControlsSAP.Controls.SAPLabel
    
    Private WithEvents txtTFG_HORASFALTADAS As ControlsSAP.Controls.SAPTextBox
    
    Private WithEvents btnOk As ControlsSAP.Controls.SAPButton
    
    Private WithEvents btnCancel As ControlsSAP.Controls.SAPButton
    
    'Form reemplaza a Dispose para limpiar la lista de componentes.
    <System.Diagnostics.DebuggerNonUserCode()>  _
    Protected Overrides Sub Dispose(ByVal disposing As Boolean)
        If disposing Then
            If (Not (components) Is Nothing) Then
                components.Dispose
            End If
        End If
        MyBase.Dispose(disposing)
    End Sub
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Private Sub InitializeComponent()
        Me.lbltxtCode = New ControlsSAP.Controls.SAPLabel()
        Me.txtCode = New ControlsSAP.Controls.SAPTextBox()
        Me.lbltxtName = New ControlsSAP.Controls.SAPLabel()
        Me.txtName = New ControlsSAP.Controls.SAPTextBox()
        Me.lbllstTFG_CODEEMP = New ControlsSAP.Controls.SAPLabel()
        Me.lstTFG_CODEEMP = New ControlsSAP.Controls.SAPListBox()
        Me.lbltxtTFG_FECHAFALTA = New ControlsSAP.Controls.SAPLabel()
        Me.txtTFG_FECHAFALTA = New ControlsSAP.Controls.SAPTextBox()
        Me.lbltxtTFG_HORASFALTADAS = New ControlsSAP.Controls.SAPLabel()
        Me.txtTFG_HORASFALTADAS = New ControlsSAP.Controls.SAPTextBox()
        Me.btnOk = New ControlsSAP.Controls.SAPButton()
        Me.btnCancel = New ControlsSAP.Controls.SAPButton()
        Me.SuspendLayout()
        '
        'lbltxtCode
        '
        Me.lbltxtCode.Location = New System.Drawing.Point(8, 30)
        Me.lbltxtCode.Margin = New System.Windows.Forms.Padding(0, 0, 0, 1)
        Me.lbltxtCode.Name = "lbltxtCode"
        Me.lbltxtCode.Size = New System.Drawing.Size(135, 14)
        Me.lbltxtCode.TabIndex = 1
        Me.lbltxtCode.Text = "Código"
        '
        'txtCode
        '
        Me.txtCode.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle
        Me.txtCode.CausesActionUpdate = True
        Me.txtCode.Enabled = False
        Me.txtCode.Location = New System.Drawing.Point(181, 30)
        Me.txtCode.Margin = New System.Windows.Forms.Padding(0, 0, 0, 1)
        Me.txtCode.MaxLength = 0
        Me.txtCode.Name = "txtCode"
        Me.txtCode.Size = New System.Drawing.Size(150, 14)
        Me.txtCode.TabIndex = 0
        '
        'lbltxtName
        '
        Me.lbltxtName.Location = New System.Drawing.Point(8, 45)
        Me.lbltxtName.Margin = New System.Windows.Forms.Padding(0, 0, 0, 1)
        Me.lbltxtName.Name = "lbltxtName"
        Me.lbltxtName.Size = New System.Drawing.Size(135, 14)
        Me.lbltxtName.TabIndex = 3
        Me.lbltxtName.Text = "Descripción"
        '
        'txtName
        '
        Me.txtName.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle
        Me.txtName.CausesActionUpdate = True
        Me.txtName.Location = New System.Drawing.Point(181, 45)
        Me.txtName.Margin = New System.Windows.Forms.Padding(0, 0, 0, 1)
        Me.txtName.MaxLength = 0
        Me.txtName.Name = "txtName"
        Me.txtName.Size = New System.Drawing.Size(150, 14)
        Me.txtName.TabIndex = 1
        '
        'lbllstTFG_CODEEMP
        '
        Me.lbllstTFG_CODEEMP.Location = New System.Drawing.Point(8, 60)
        Me.lbllstTFG_CODEEMP.Margin = New System.Windows.Forms.Padding(0, 0, 0, 1)
        Me.lbllstTFG_CODEEMP.Name = "lbllstTFG_CODEEMP"
        Me.lbllstTFG_CODEEMP.Size = New System.Drawing.Size(135, 14)
        Me.lbllstTFG_CODEEMP.TabIndex = 5
        Me.lbllstTFG_CODEEMP.Text = "Code Empleado Dep Ventas"
        '
        'lstTFG_CODEEMP
        '
        Me.lstTFG_CODEEMP.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle
        Me.lstTFG_CODEEMP.CausesActionUpdate = True
        Me.lstTFG_CODEEMP.Location = New System.Drawing.Point(181, 60)
        Me.lstTFG_CODEEMP.Margin = New System.Windows.Forms.Padding(0, 0, 0, 1)
        Me.lstTFG_CODEEMP.Name = "lstTFG_CODEEMP"
        Me.lstTFG_CODEEMP.Size = New System.Drawing.Size(150, 14)
        Me.lstTFG_CODEEMP.TabIndex = 2
        '
        'lbltxtTFG_FECHAFALTA
        '
        Me.lbltxtTFG_FECHAFALTA.Location = New System.Drawing.Point(8, 75)
        Me.lbltxtTFG_FECHAFALTA.Margin = New System.Windows.Forms.Padding(0, 0, 0, 1)
        Me.lbltxtTFG_FECHAFALTA.Name = "lbltxtTFG_FECHAFALTA"
        Me.lbltxtTFG_FECHAFALTA.Size = New System.Drawing.Size(135, 14)
        Me.lbltxtTFG_FECHAFALTA.TabIndex = 7
        Me.lbltxtTFG_FECHAFALTA.Text = "Fecha del día de la falta"
        '
        'txtTFG_FECHAFALTA
        '
        Me.txtTFG_FECHAFALTA.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle
        Me.txtTFG_FECHAFALTA.CausesActionUpdate = True
        Me.txtTFG_FECHAFALTA.DataType = ControlsSAP.Controls.SAPTextBox.DataTypes.Fecha
        Me.txtTFG_FECHAFALTA.Location = New System.Drawing.Point(181, 75)
        Me.txtTFG_FECHAFALTA.Margin = New System.Windows.Forms.Padding(0, 0, 0, 1)
        Me.txtTFG_FECHAFALTA.MaxLength = 10
        Me.txtTFG_FECHAFALTA.Name = "txtTFG_FECHAFALTA"
        Me.txtTFG_FECHAFALTA.Size = New System.Drawing.Size(150, 14)
        Me.txtTFG_FECHAFALTA.TabIndex = 3
        '
        'lbltxtTFG_HORASFALTADAS
        '
        Me.lbltxtTFG_HORASFALTADAS.Location = New System.Drawing.Point(8, 90)
        Me.lbltxtTFG_HORASFALTADAS.Margin = New System.Windows.Forms.Padding(0, 0, 0, 1)
        Me.lbltxtTFG_HORASFALTADAS.Name = "lbltxtTFG_HORASFALTADAS"
        Me.lbltxtTFG_HORASFALTADAS.Size = New System.Drawing.Size(135, 14)
        Me.lbltxtTFG_HORASFALTADAS.TabIndex = 9
        Me.lbltxtTFG_HORASFALTADAS.Text = "Horas faltadas"
        '
        'txtTFG_HORASFALTADAS
        '
        Me.txtTFG_HORASFALTADAS.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle
        Me.txtTFG_HORASFALTADAS.CausesActionUpdate = True
        Me.txtTFG_HORASFALTADAS.DataType = ControlsSAP.Controls.SAPTextBox.DataTypes.Numero
        Me.txtTFG_HORASFALTADAS.Location = New System.Drawing.Point(181, 90)
        Me.txtTFG_HORASFALTADAS.Margin = New System.Windows.Forms.Padding(0, 0, 0, 1)
        Me.txtTFG_HORASFALTADAS.MaxLength = 0
        Me.txtTFG_HORASFALTADAS.Name = "txtTFG_HORASFALTADAS"
        Me.txtTFG_HORASFALTADAS.Size = New System.Drawing.Size(150, 14)
        Me.txtTFG_HORASFALTADAS.TabIndex = 4
        '
        'btnOk
        '
        Me.btnOk.Location = New System.Drawing.Point(8, 115)
        Me.btnOk.Name = "btnOk"
        Me.btnOk.Size = New System.Drawing.Size(75, 20)
        Me.btnOk.TabIndex = 5
        Me.btnOk.Text = "OK"
        Me.btnOk.UseVisualStyleBackColor = False
        '
        'btnCancel
        '
        Me.btnCancel.Location = New System.Drawing.Point(90, 115)
        Me.btnCancel.Name = "btnCancel"
        Me.btnCancel.Size = New System.Drawing.Size(75, 20)
        Me.btnCancel.TabIndex = 6
        Me.btnCancel.Text = "Cancel"
        Me.btnCancel.UseVisualStyleBackColor = False
        '
        'frmFaltasEDV
        '
        Me.AcceptsAdd = True
        Me.AcceptsDelete = True
        Me.AcceptsSearch = True
        Me.AcceptsUpdate = True
        Me.AutoScaleDimensions = New System.Drawing.SizeF(6.0!, 12.0!)
        Me.ButtonForm = Me.btnOk
        Me.ClientSize = New System.Drawing.Size(342, 146)
        Me.Controls.Add(Me.lbltxtCode)
        Me.Controls.Add(Me.txtCode)
        Me.Controls.Add(Me.lbltxtName)
        Me.Controls.Add(Me.txtName)
        Me.Controls.Add(Me.lbllstTFG_CODEEMP)
        Me.Controls.Add(Me.lstTFG_CODEEMP)
        Me.Controls.Add(Me.lbltxtTFG_FECHAFALTA)
        Me.Controls.Add(Me.txtTFG_FECHAFALTA)
        Me.Controls.Add(Me.lbltxtTFG_HORASFALTADAS)
        Me.Controls.Add(Me.txtTFG_HORASFALTADAS)
        Me.Controls.Add(Me.btnOk)
        Me.Controls.Add(Me.btnCancel)
        Me.MaximumSize = New System.Drawing.Size(358, 162)
        Me.Name = "frmFaltasEDV"
        Me.Text = "Faltas empleados dep. ventas"
        Me.Controls.SetChildIndex(Me.btnCancel, 0)
        Me.Controls.SetChildIndex(Me.btnOk, 0)
        Me.Controls.SetChildIndex(Me.txtTFG_HORASFALTADAS, 0)
        Me.Controls.SetChildIndex(Me.lbltxtTFG_HORASFALTADAS, 0)
        Me.Controls.SetChildIndex(Me.txtTFG_FECHAFALTA, 0)
        Me.Controls.SetChildIndex(Me.lbltxtTFG_FECHAFALTA, 0)
        Me.Controls.SetChildIndex(Me.lstTFG_CODEEMP, 0)
        Me.Controls.SetChildIndex(Me.lbllstTFG_CODEEMP, 0)
        Me.Controls.SetChildIndex(Me.txtName, 0)
        Me.Controls.SetChildIndex(Me.lbltxtName, 0)
        Me.Controls.SetChildIndex(Me.txtCode, 0)
        Me.Controls.SetChildIndex(Me.lbltxtCode, 0)
        Me.ResumeLayout(False)

    End Sub
End Class
